#! /usr/bin/env bash

ME=$(basename $0)
BASE=$(readlink -f $(dirname $0)/..)

dna_seq="TAGATTAGTCATCTGATGCGCCGCTACAGACATGTATGCGGGAGTTTCATGGGGGCGAAGTCAGTATCGCCGAATGGCTATCCTCTAATAGGCAGAATCTTGAAGGCGCCACGGTTCTAACATTGTACCAACTTAGCTCCAATACAATTTCATATCACGTTAGCAGCTAGTCACCCAATCTCTAAGCATTGGGGGCATTAGCGCGACAGCTTGGCGGTGTGATTTCGAATTTACATGAGATCAAATCTTATGAAGGCGGCTCTAATGGCTTGTGTCCTTCGAGGTAGAGCGCTAGCTGGCCTTTGAAAAAACTCCCGCGCGGTAGACTCTGTGGATTCTGCTATACGAAACTCTACCCCTGCAACAGGCCTTATTCCGGCGCCATTGGAGAAAGTCCCGCCTACGTGTTGTGGGACGAGCAAATATGGACGGGACCTCGAAGTGTACTTTATATGTCTCGTTGCTGCGTGATTCAGACCAGCAAGGTTAACTAACTTATCAACCTCGCCCTCGAGCGCTTCATCAAGCCGCCGACGCGTGGCCATACGGTGGCCATTTTGACCATTGGATCTCCAACCCAAGTTGCAGCTTCACAGTAGGGTTGACCTTCACTTCCATCACCCGAGCGAAAGAAAGACGACGGCCCATCTGCCAATGTGACCGGGTCGTAGAATTGCAACCACTGTCTGCTCAAGTTCCATTGTAGAGTCAACAAAAATTGGAACGACCATTTAATTGCGGGCGCTACAGAACGCCATTAGTTGTAAACCCGGTCTCTTAGACGCGATAGCTCATTGGCATAACGTTCCACTTTCAATCCATAGACGGTCCCGCTTGAACAGAATAAGGAATTCGAGATGATCCCACAACACAGCTGTACCGTATGACACGTGGTTATGCCTATTCCCCCGCAATCGGAGCTGGTTTTGTAGATATGCTT"

# echo $dna_seq

ltrs=("A" "C" "G" "T")
# val=${ltrs[0]}

for i in ${ltrs[@]}; do
  num=$(grep -o "$i" <<< "$dna_seq" | wc -l)
  echo "$i: $num"
done

